name: her
services:
    selkies:
        container_name: egl
        stdin_open: true
        tty: true
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities:
                              - gpu
        tmpfs: /dev/shm:rw
        environment:
            - TZ=UTC
            - DISPLAY_SIZEW=1920
            - DISPLAY_SIZEH=1080
            - DISPLAY_REFRESH=60
            - DISPLAY_DPI=96
            - DISPLAY_CDEPTH=24
            - PASSWD=mypasswd
            - SELKIES_ENCODER=nvh264enc
            - SELKIES_VIDEO_BITRATE=50000
            - SELKIES_FRAMERATE=60
            - SELKIES_AUDIO_BITRATE=128000
            - SELKIES_BASIC_AUTH_PASSWORD=mypasswd
            - SELKIES_TURN_HOST=<TURN_IP>
            - SELKIES_TURN_SHARED_SECRET=n0TaRealCoTURNAuthSecretThatIsSixtyFourLengthsLongPlaceholdPlace
        ports:
            - 8080:8080
        volumes:
        # For building conda packages
            - pkgs:/pkgs_repo
            - build-cache:/home/ubuntu/miniconda3/conda-bld
        image: <DOCKER_IMAGE>

    coturn:
        container_name: coturn
        stdin_open: true
        tty: true
        environment:
            - TURN_SHARED_SECRET=n0TaRealCoTURNAuthSecretThatIsSixtyFourLengthsLongPlaceholdPlace
            - TURN_REALM=example.com
            - TURN_PORT=3478
            - TURN_MIN_PORT=65500
            - TURN_MAX_PORT=65535
        ports:
            - 3478:3478
            - 3478:3478/udp
            - 65500-65535:65500-65535
            - 65500-65535:65500-65535/udp
        image: ghcr.io/selkies-project/selkies-gstreamer/coturn:main